### PR TITLE
add service

### PR DESCRIPTION
**Pull request by SobirjonovSodiqjonovich**
Configure Identity server

### CODE REVIEW

**Review by mrakhmadjon — COMMENTED** [review]
kordim

**Comment by SobirjonovSodiqjonovich** [comment]
Kordim

**Review by SobirjonovSodiqjonovich — COMMENTED** [review]
wvwevwvwev

**Review by mrakhmadjon — CHANGES_REQUESTED** [review]
w

**Review by mrakhmadjon — APPROVED** [review]
a

**Pull request merged**
